FROM node:8.9-alpine
ENV NODE_ENV production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --silent && mv node_modules ../
RUN npm install -g babel-cli
RUN ls
COPY . .
RUN npm run build
EXPOSE 3001
CMD npm run start:prod